kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 1 control-plane and 1 worker
nodes:
- role: control-plane
  # Make port 30000 from inside the cluster accessible to localhost:3000
  extraPortMappings:
  - containerPort: 30000
    hostPort: 3000
    protocol: TCP
- role: worker
