---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: python-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: python-service
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app.kubernetes.io/name: python-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: python-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: python-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: python-service
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-service
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - image: kenf/python-service:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: python-service
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
