---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: another-node-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: another-node-service
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: another-node-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: another-node-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: another-node-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: another-node-service
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: another-node-service
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - image: kenf/another-node-service:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: another-node-service
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
